drop table if exists book_entity cascade ;
drop table if exists user_entity cascade ;
drop table if exists user_entity_taken_books cascade ;
create table book_entity (
    id bigint generated by default as identity
    , issue_date timestamp(6)
    , publication_date timestamp(6)
    , author varchar(255)
    , name varchar(255)
    , primary key (id));
create table user_entity (
    ticket_number uuid not null
    , user_name varchar(255)
    , primary key (ticket_number));
create table user_entity_taken_books (
    taken_books_id bigint not null unique
    , user_entity_ticket_number uuid not null
    , primary key (taken_books_id, user_entity_ticket_number));
alter table if exists user_entity_taken_books add constraint FKq3d2h965hr9i8lrast7y8thwx foreign key (taken_books_id) references book_entity;
alter table if exists user_entity_taken_books add constraint FKkafudkvwga5754r6clxu4x5l1 foreign key (user_entity_ticket_number) references user_entity;
